HOME_ANGLE = 45; // degrees
HOME_ANIM_RANGE = 90; // degrees
DEFAULT_ANIM_RANGE = 360; // degrees
COLUMN_REFRESH_STEPS=(HOME_ANIM_RANGE+DEFAULT_ANIM_RANGE+HOME_ANIM_RANGE)/HOME_ANIM_RANGE;
CRANK_ARM = 8; // in mm
SERVO_ARM = 16; // in mm
time = $t;